baseURL: https://joshbielick.com
title: Josh Bielick
theme: dimension
googleAnalytics: UA-11539854-4
languageCode: en-us
defaultContentLanguage: en
enableRobotsTXT: true
disableKinds:
  - RSS
params:
  description: >
    Ever-curious creator and collaborator. Software, team, and systems developer.
    <br>
    Senior Systems Engineer, Security Platform at <a href="https://www.cloudflare.com/" target="_blank">Cloudflare</a>,
    Durham, NC
  logoimage: "/images/headshot.jpg"
  copyright: "2024 Josh Bielick"
  social:
    - medium: twitter
      icon: twitter
      link: https://twitter.com/jbielick
    - medium: stackoverflow
      icon: stack-overflow
      link: https://stackoverflow.com/users/3543371/jbielick
    - medium: vimeo
      icon: vimeo
      link: https://vimeo.com/jbielick
    - medium: flickr
      icon: flickr
      link: https://www.flickr.com/photos/jbielick
    - medium: soundcloud
      icon: soundcloud
      link: https://soundcloud.com/leo-tallstoy
languages:
  en:
    languageName: English
    weight: 1
