baseURL: https://joshbielick.com/
title: Josh Bielick
theme: dimension
googleAnalytics: UA-11539854-4
languageCode: en-us
defaultContentLanguage: en
enableRobotsTXT: true
disableKinds:
  - RSS
params:
  description: >
    Ever-curious software developer, creator, and collaborator
    <br>
    primarily writing in JavaScript, Ruby, Go, bash, and SQL.
    <br>
    CTO at <a href="https://www.adwerx.com" target="_blank">Adwerx</a>,
    Durhamite
  logoimage: "/images/headshot.jpg"
  copyright: "2018 Josh Bielick"
  social:
    - medium: twitter
      icon: twitter
      link: https://twitter.com/jbielick
    - medium: vimeo
      icon: vimeo
      link: https://vimeo.com/jbielick
    - medium: flickr
      icon: flickr
      link: https://www.flickr.com/photos/jbielick
    - medium: soundcloud
      icon: soundcloud
      link: https://soundcloud.com/leo-tallstoy
languages:
  en:
    languageName: English
    weight: 1
